# exception handling

try:  # will generate an exception, x is not defined
    print(x)
except:
    print("an exception occured")
